name: Deploy to Development

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          submodules: true
          lfs: false

      - name: Install Dependencies
        run: npm install

      - name: Generate Version from Changeset
        run: |
          npx changeset version
          VERSION=$(node -p "require('./package.json').version")
          echo "FRONTEND_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Commit and Push Version Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json CHANGELOG.md
          git commit -m "chore: bump version package to $FRONTEND_VERSION [skip ci]" || echo "No changes to commit"
          git push origin main || echo "No changes to push"

      - name: Build App for DEV
        run: npm run build
        env:
          NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL_DEV }}
          FRONTEND_VERSION: ${{ env.FRONTEND_VERSION }}

      - name: Zip DEV build output
        run: |
          cd out
          zip -r ../frontend-${{ env.FRONTEND_VERSION }}.zip .

      - name: Upload DEV build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-${{ env.FRONTEND_VERSION }}
          path: frontend-${{ env.FRONTEND_VERSION }}.zip

      - name: Create GitHub Release for DEV build
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.FRONTEND_VERSION }}
          name: Release ${{ env.FRONTEND_VERSION }} - ${{ github.run_number}}
          files: frontend-${{ env.FRONTEND_VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to DEV
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_DESERT_0EF514F10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "out"
        env:
          NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL_DEV }}
          FRONTEND_VERSION: ${{ env.FRONTEND_VERSION }}

      - name: Build App for QA
        run: npm run build
        env:
          NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL_QA }}
          FRONTEND_VERSION: ${{ env.FRONTEND_VERSION }}

      - name: Zip QA build output
        run: |
          cd out
          zip -r ../frontend-qa-${{ env.FRONTEND_VERSION }}.zip .

      - name: Upload QA build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-qa-${{ env.FRONTEND_VERSION }}
          path: frontend-qa-${{ env.FRONTEND_VERSION }}.zip

      - name: Create GitHub Release for QA build
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.FRONTEND_VERSION }}-qa
          name: Release QA ${{ env.FRONTEND_VERSION }} - ${{ github.run_number}}
          files: frontend-qa-${{ env.FRONTEND_VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_DESERT_0EF514F10 }}
          action: "close"
          app_location: "/"
          api_location: ""
          output_location: "./out"
