name: Deploy to QA
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy to QA"
        required: false
jobs:
  build_and_deploy_qa:
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Set Version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            VERSION="${{ github.event.inputs.version }}"
            echo "Using provided version: $VERSION"
          else
            VERSION=$( node -p "require('./package.json').version")
            echo "Version not provided. Using package.json version: $VERSION"
          fi
          echo "FRONTEND_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Download artifact from GitHub Release
        run: |
          VERSION=${{ github.event.inputs.version }}
          curl -L -o frontend-$VERSION.zip \
            https://github.com/StefanoFalconi2001/poc-weather-app/releases/download/v$VERSION/frontend-$VERSION.zip
          unzip frontend-$VERSION.zip -d ./out
